In [1]:
import pandas as pd
import numpy as np
from sklearn import  linear_model
from word2number import w2n

In [6]:
df = pd.read_excel(r"C:\Users\91829\Downloads\hiring (1).xlsx")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9    5000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [7]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9    5000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [8]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9    5000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    NaN                           7   72000
7          11                    7.0                           8   80000

In [9]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [10]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9    5000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    7.0                           7   72000
7          11                    7.0                           8   80000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)',
           'interview_score(out of 10)']],df['salary'])

LinearRegression()

In [12]:
reg.predict([[2,9,6]])

array([48341.3241036])

In [13]:
reg.predict([[4,10,34]])

array([75142.24821401])

In [14]:
import pickle

In [26]:
with open('df', 'wb') as file:
    pickle.dump(reg,file)

In [27]:
with open('df', 'rb') as f:
    mp = pickle.load(f)

In [42]:
mp.predict([[2 , 6 ,3]])

array([36164.85652419])

In [29]:
mp.coef_

array([4556.25650032, 3554.02294931,  504.79957716])

In [34]:
import joblib 

In [37]:
joblib.dump(df, 'model_job')

['model_job']

In [39]:
mj = joblib.load('model_job')

In [41]:
mj.predict([[2, 4, 6]])

AttributeError: 'DataFrame' object has no attribute 'predict'